In [ ]:
import torch
import numpy as np

In [ ]:
torch.__version__

'2.8.0+cu126'

## **Playing around with tensors**


In [ ]:
#default torch.Tensor is a float32

t1 = torch.Tensor([1.7234, 2.2637178923, 3.16782376812]) #
array_np = np.array([4.0, 3.0, 2.0])

#some diferent tensor types
t2 = torch.IntTensor(array_np) #converts default float32 to int32
t3 = torch.DoubleTensor(array_np) #float64
t4 = torch.BoolTensor([0,1,0,0,0,0,3,2,1, 9123891231231.1231])
t5 = torch.LongTensor(array_np)
t6 = torch.ShortTensor(array_np)

print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print("tensor type:", t4.dtype, "===","tensor values: ", t4)
print(t6.dtype)
print(t5.dtype)

#complex number

t = torch.Tensor([1, 2])
t_complex = torch.view_as_complex(t)
print("\n", "complex:", "\n", t_complex)
print(t_complex.dtype)


torch.float32
torch.int32
torch.float64
tensor type: torch.bool === tensor values:  tensor([False,  True, False, False, False, False,  True,  True,  True,  True])
torch.int16
torch.int64

 complex: 
 tensor(1.+2.j)
torch.complex64


In [ ]:
#converting tensors to other dtypes

# t1.int()
t1.double()

tensor([1.7234, 2.2637, 3.1678], dtype=torch.float64)

In [ ]:
t01 = torch.Tensor([5,2,3])
t02 = torch.Tensor([2,10,2])

tensor([ 7., 12.,  5.])

### **Simple operations**

In [ ]:
#sum
print("sum: ", t01 + t02)

#subtraction
print ("sub: ", t01 - t02)

#mult
print ("mult: ", t01 * t02)

#divide
print ("div: ", t01 / t02)

sum:  tensor([ 7., 12.,  5.])
sub:  tensor([ 3., -8.,  1.])
mult:  tensor([10., 20.,  6.])
div:  tensor([2.5000, 0.2000, 1.5000])


### **Matrix operations**

In [ ]:
t01 = torch.Tensor([1, 4])
t02 = torch.Tensor([[1,2],[3,2]])

In [ ]:
t01

tensor([1., 4.])

In [ ]:
t02

tensor([[1., 2.],
        [3., 2.]])

In [ ]:
t01.shape[0] == t02.shape[0]

True

In [ ]:
#dot product
t01.matmul(t02)

tensor([13., 10.])

## **Grads and Autograd**


In [ ]:
x = torch.Tensor([2.0])
x.requires_grad = True
x

tensor([2.])

In [ ]:


y = x**3
y

tensor([8.], grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor([12.])

## **Simple NN**

In [ ]:
inputs = torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
targets = torch.tensor([[0.0], [1.0], [1.0], [0.0]])

In [ ]:
import torch.nn as nn
import torch.optim as optim

### **Model creation**

In [ ]:
class Model(nn.Module):
  def __init__(self):
    #herdando o construtor da classe pai
    super().__init__()
    self.fc1 = nn.Linear(in_features=2, out_features=2)
    self.fc2 = nn.Linear(in_features=2, out_features=1)


  def forward(self, x):
    x = self.fc1(x)
    x = torch.relu(x)
    x = self.fc2(x)
    return x

  def bwd():
    pass

In [ ]:
model = Model()
[i for i in model.parameters()]

[Parameter containing:
 tensor([[ 0.4460, -0.3057],
         [ 0.6692, -0.2815]], requires_grad=True),
 Parameter containing:
 tensor([-0.3774,  0.1099], requires_grad=True),
 Parameter containing:
 tensor([[ 0.4941, -0.1813]], requires_grad=True),
 Parameter containing:
 tensor([0.2690], requires_grad=True)]

In [ ]:
loss_fn = nn.MSELoss()
opt = optim.Adam(params=model.parameters(), lr=0.01)

In [ ]:
for epoch in range(100):
  pred = model(inputs)
  loss = loss_fn(pred, targets)
  loss.backward()
  opt.step()
  opt.zero_grad()

  if (epoch+1) % 5 == 0:
    print("Epoch: ", (epoch+1), "loss: ", loss.item())


Epoch:  5 loss:  0.2830219268798828
Epoch:  10 loss:  0.23733428120613098
Epoch:  15 loss:  0.21183708310127258
Epoch:  20 loss:  0.20222578942775726
Epoch:  25 loss:  0.19351215660572052
Epoch:  30 loss:  0.18791821599006653
Epoch:  35 loss:  0.18256153166294098
Epoch:  40 loss:  0.17532816529273987
Epoch:  45 loss:  0.16861900687217712
Epoch:  50 loss:  0.16271620988845825
Epoch:  55 loss:  0.1561567783355713
Epoch:  60 loss:  0.14918047189712524
Epoch:  65 loss:  0.14215372502803802
Epoch:  70 loss:  0.13512545824050903
Epoch:  75 loss:  0.12710599601268768
Epoch:  80 loss:  0.11917761713266373
Epoch:  85 loss:  0.11091387271881104
Epoch:  90 loss:  0.10244061052799225
Epoch:  95 loss:  0.09427161514759064
Epoch:  100 loss:  0.08590701222419739
